### ISSUE TITLE
enable flag for test differs from intel-vaapi-driver

### ISSUE THREAD

**Issue by seanvk** [01org/libva-utils#12]
To stay consistent with intel-vaapi-driver, can we change the tests enable flag to --enable-tests?

**Comment by seanvk** [comment]
currently it's:  --enable-gtests
and the text printed is "Enable Gtests"

**Comment by uartie** [comment]
Agree... if we decide to use a different test framework down the road then `--enable-tests` will remain valid.

**Comment by chivakker** [comment]
This was the reasoning behind the name:

libva-utils contains a group of tests and also gtests, tests that run using Google test framework.  By default, libva-utils builds other tests applications, i.e. vainfo, while --enable-gtests does enable only gtests.

Using --enable-tests could cause confusion to people that want to use only the tests and not deploy gtests.

But I agree that keeping compatibility is desirable.

**Comment by uartie** [comment]
IMO, I wouldn't categorize vainfo et.al. as tests.  Rather, utilities or examples.

**Comment by chivakker** [comment]
yes that's what they are (examples)  but people call them tests. In reality it suffices that there's a record of this decision and I'll add it to the commit message.

**Comment by uartie** [comment]
perhaps change it to --enable-conformance?  And do away with "tests" term for everything?
