### ISSUE TITLE
test failures when hybrid-codec enabled

### ISSUE THREAD

**Issue by uartie** [01org/libva-utils#14]
When intel-vaapi-driver is compiled with `--enable-hybrid-codec` and intel-hybrid-driver is present, the intel-vaapi-driver loads the hybrid driver.  This causes the following test cases to fail:

GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/199
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/200
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/201
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/202
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/203
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/204
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/205
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigNoAttributes/206
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/198
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/199
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/200
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/201
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/202
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/203
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/204
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/205
GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/206

...with the following error messages:

test_va_api_fixture.cpp:496: Failure
      Expected: vaStatus
      Which is: 13
To be equal to: error
      Which is: 12

**Comment by seanvk** [comment]
Hybrid Encode is ONLY supported on BSW, BDW and SKL on ChromeOS.  Currently we have also deprecated in ChromeOS SKL support.

**Comment by seanvk** [comment]
Hybrid Encode is not supported at all.  Although anyone is free to play with it.  This driver is only for Chrome hybrid decode.

**Comment by uartie** [comment]
ok, use case not supported
