### ISSUE TITLE
avcenc.c:236:32: error: ‘struct <anonymous>’ has no member named ‘roi_rc_qp_delat_support’

### ISSUE THREAD

**Issue by kclim2** [01org/libva-utils#18]
`Making all in encode
make[2]: Entering directory `/home/ubuntu/Downloads/libva-utils/encode'
  CC       avcenc-avcenc.o
avcenc.c: In function ‘create_encode_pipe’:
avcenc.c:236:32: error: ‘struct <anonymous>’ has no member named ‘roi_rc_qp_delat_support’
                roi_config->bits.roi_rc_qp_delat_support == 0) {
                                ^
avcenc.c: In function ‘begin_picture’:
avcenc.c:861:27: error: ‘VAEncMiscParameterBufferROI’ has no member named ‘roi_flags’
             misc_roi_param->roi_flags.bits.roi_value_is_qp_delta = 1;
                           ^
make[2]: *** [avcenc-avcenc.o] Error 1
make[2]: Leaving directory `/home/ubuntu/Downloads/libva-utils/encode'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/Downloads/libva-utils'
make: *** [all] Error 2
`

libva-utils - 1.8.0.pre2

Libva VA-API version ............. : 0.99.0
Installation prefix .............. : /usr/local
Extra window systems ............. : drm
Enable Unit-tests .................... : yes

**Comment by yakuizhao** [comment]
It seems that you are using the unmatched libva version with libva-utils.

**Comment by chivakker** [comment]
yes, va-api version should never read 0.99.0

**Comment by kclim2** [comment]
0.99.0 is defined in /opt/intel/mediasdk/opensource/libva/1.67.0.pre1-55964/libva-1.67.0.pre1/va/va_version.h where we installed from MediaServerStudioProfessionalEvaluation2017.tar.gz (Production 16.5)

`/**
 * VA_VERSION:
 *
 * The full version of VA-API, like 1.2.3
 */
#define VA_VERSION          0.99.0
`
Anything wrong from my side?

**Comment by chivakker** [comment]
I don't think a newer release or ToT from libva, intel-vaapi-driver and libva-utils will work with that old version of libva.  Your package requires an update.

**Comment by kclim2** [comment]
I'm confused. we are using the latest Intel Media Server studio R2 (
MediaServerStudioProfessionalEvaluation2017.tar.gz).  is the libva comes
together with MediaServerStudioProfessionalEvaluation2017.tar.gz R2 not the
latest version?

**Comment by chivakker** [comment]
I don't know what they package, maybe you want to ask them if you can use upstream libva and intel-vaapi-driver.

**Comment by xhaihao** [comment]
@kclim2  The latest *stable* VA API version is 0.40.
