### ISSUE TITLE
libva error: dlopen of /opt/intel/mediasdk/lib64/iHD_drv_video.so failed: /opt/intel/mediasdk/lib64/iHD_drv_video.so: undefined symbol: drm_intel_gem_bo_unmap_wc

### ISSUE THREAD

**Issue by kclim2** [01org/libva-utils#19]
`
vainfo
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva error: dlopen of /opt/intel/mediasdk/lib64/iHD_drv_video.so failed: /opt/intel/mediasdk/lib64/iHD_drv_video.so: undefined symbol: drm_intel_gem_bo_unmap_wc
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
`

**Comment by xhaihao** [comment]
@kclim2 I do not support  iHD.

**Comment by chivakker** [comment]
@kclim2 this is the same question you'd need to ask to your package providers.

**Comment by scott-d-phillips** [comment]
@kclim2, just a little more explanation: libva is a generic library for video encode/decode/processing that works with multiple hardware accelerators. libva and libva-utils are both device independent pieces that applications can use. libva itself then dispatches the actual work of interfacing to hardware to a separate driver library (iHD_drv_video.so in your log). There is an open source driver at https://github.com/01org/intel-vaapi-driver. However the iHD driver is not open source, so for support for driver specific issues you will need to go through the Media Server Studio support channels.

**Comment by kclim2** [comment]
anyway, i do have i965_drv_video.la and i965_drv_video.so in my /opt/intel/mediasdk/lib64 which i build with  https://github.com/01org/intel-vaapi-driver .

how can i force libva to use he i965* driver but not the iHD?

**Comment by uartie** [comment]
export LIBVA_DRIVER_NAME=i965

**Comment by kclim2** [comment]
great, it works!

`vainfo
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /opt/intel/mediasdk/lib64/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva 1.67.0.pre1)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 1.8.0.pre1 (1.7.3-340-ga751713)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	<unknown entrypoint>
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	<unknown entrypoint>
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	<unknown entrypoint>
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
`
Many  Thanks!

**Comment by xhaihao** [comment]
@kclim2 It is possible mediasdk doesn't work well with intel-vaapi-driver (i965). You should ping your package provider for help.

**Comment by jkldgoefgkljefogeg** [comment]
It can be a permission issue.
