### ISSUE TITLE
"skipped" should be recorded in xml output

### ISSUE THREAD

**Issue by uartie** [01org/libva-utils#2]
When a test is skipped, we should call `RecordProperty("skipped", true);` so that this information is recorded in the xml output results.  This will allow for xml post-processing scripts to detect skipped tests.  For example, junit parsers can report skipped tests when a `<skipped/>` tag exists in the xml output.  Unfortunately, gtest doesn't support skipped tests directly (nor does it allow adding extra tags to the xml output)... but if we record this information in an attribute of the xml test report (i.e. via a call to gtest's `RecordProperty` method), then we can post process the output and move the information to an inner tag when we want junit parsers to recognize skipped tests.

**Comment by chivakker** [comment]
patch proposed on github, please review.
