### ISSUE TITLE
The tarball created by 'make dist' is still uncompilable

### ISSUE THREAD

**Issue by xhaihao** [01org/libva-utils#26]
CXX      test_va_api-test_va_api_fixture.o
In file included from test_va_api_fixture.cpp:25:0:
test_va_api_fixture.h:27:23: fatal error: test_data.h: No such file or directory
 #include "test_data.h"
                       ^
compilation terminated.

**Comment by xhaihao** [comment]
CC       h264encode-h264encode.o
h264encode.c:48:25: fatal error: loadsurface.h: No such file or directory
 #include "loadsurface.h"
                         ^
compilation terminated.

**Comment by chivakker** [comment]
This error was caused by the patch not ported back to master branch from release branch.  Once the patch is amended, I'll cherry-pick the patch to the release branch.

**Comment by xhaihao** [comment]
loadsurface.h was added on release branch but test_data.h wasn't added. I will update the patch.
