### ISSUE TITLE
Why don't have H.264 decode sample

### ISSUE THREAD

**Issue by lichangqing2611** [01org/libva-utils#47]
Hello, partner. I find h.264 encode sample, but I can't find h.264 decode sample. Please supply h.264 encode sample, Thank you !

**Comment by QuPengfei** [comment]
@lichangqing2611 
Please refer to "yamidecode" in the following, 
https://github.com/01org/libyami-utils
https://github.com/01org/libyami

**Comment by xhaihao** [comment]
VAAPI uses the similar function call sequence for decoding pipeline for each codec. You can refer to mpeg2vldemo for the program flow. You can refer to https://github.com/01org/libyami and https://github.com/01org/libyami-utils for how a vaapi h.264 decoder works
