### ISSUE TITLE
h264encode.c: VA_ENC_SLICE_STRUCTURE_ARBITRARY_ROWS makes no sense

### ISSUE THREAD

**Issue by mleise** [01org/libva-utils#54]
I think maybe VA_ENC_SLICE_STRUCTURE_ARBITRARY_ROWS was supposed to be non-zero, but right now this is an always false comparison:
https://github.com/01org/libva-utils/blob/c9af683d6cb1f7d79ac0a300cc0f586569466738/encode/h264encode.c#L1246
I was about to write similar code and couldn't get my head around how it is supposed to be used. Maybe it should be redefined to be `0x00000004`... ?

**Comment by xhaihao** [comment]
Yes, it should be a non-zero, and https://github.com/01org/libva/pull/82 fixed this issue, the patch will be merged into the new library.

**Comment by mleise** [comment]
Alright, didn't see the pull request. Thx for the heads up.
