### ISSUE TITLE
TEST_P(VAAPIGetCreateConfig, CreateConfigWithAttributes) 

### ISSUE THREAD

**Issue by XinfengZhang** [01org/libva-utils#86]
this test call (line 63/66 of test_va_api_get_create_config.cpp)
doGetConfigAttributes(currentProfile,currentEntrypoint);
doCreateConfigWithAttrib(currentProfile,currentEntrypoint);
I don't think that the attributes from vaGetConfigAttributes can be directly used for vaCreateConfig
for example:
if (attrib[type] == VAConfigAttribRateControl && attrb[value] == 0x6) it means VBR & CBR support, but not mean you can set VBR|CBR directly to vaCreateConfig, right?

**Comment by uartie** [comment]
Yes, you are right.  Applications should only set one value for rate control.  We will get it fixed.
