### ISSUE TITLE
TEST_P(VAAPICreateBuffer, CreateBufferWithOutData) failed 

### ISSUE THREAD

**Issue by XinfengZhang** [01org/libva-utils#88]
test_va_api_createbuffer.cpp line 171 doCreateContext(Resolution(1, 1)); not check the min resolution, it will failed. then cause CreateBuffer test failed.

**Comment by uartie** [comment]
Agree.  Will fix.

**Comment by jayesht** [comment]
vaQuerySurfaceAttributes() as implemented in intel-vaapi-driver does not return surface attributesVASurfaceAttribMinHeight and  VASurfaceAttribMinWidth.
Not sure if driver supports any other api that can be used to get min resolution supported by the driver?

**Comment by uartie** [comment]
@jayesht actually, `vaQuerySurfaceAttributes` *does* provide Min/Max Width/Height.  This is how the CreateContext test gets them.

**Comment by uartie** [comment]
@jayesht my bad, you are right.  The intel-vaapi-driver does not specify min width/height, only max width/height (which is where I got confused).  Hence, as stated earlier, 1,1 should be assumed by app.

In the case of iHD, they do return min width/height... and therefore we need to check it.
